/**
 * PRIMA: Age of Bronze - 20 Skills & 500 Unlocks Matrix
 * 20 Skills across 10 Tiers (Levels 1 to 50), each with exactly 25 unlocks.
 */

export const SKILL_DEFINITIONS = {
  hunting: {
    id: 'hunting',
    name: 'Hunting',
    icon: '🏹',
    category: 'Combat',
    description: 'Mastery of spears, tracking primeval beasts, ranged bows, and beast hunting.',
    unlocks: [
      { lvl: 1, name: 'Flint Spear Mastery', desc: 'Wield basic flint tipped spears effectively.' },
      { lvl: 2, name: 'Dire Wolf Tracking', desc: 'Sense dire wolf pack spawns and movements.' },
      { lvl: 4, name: 'Beast Pheromones I', desc: 'Bait small game with natural scents.' },
      { lvl: 6, name: 'Saber Raptor Harpoon', desc: 'Penetrate light reptile scales with ranged strikes.' },
      { lvl: 8, name: 'Eagle Eye Stance', desc: '+5% ranged accuracy when stationary.' },
      { lvl: 10, name: 'Mammoth Flanking', desc: 'Deal +15% damage when attacking beasts from behind.' },
      { lvl: 12, name: 'Bone Recurve Bow', desc: 'Craft and wield reinforced bone bows.' },
      { lvl: 14, name: 'Bleed Shot', desc: 'Chance to inflict bleeding damage over 3 ticks.' },
      { lvl: 16, name: 'Cave Bear Tracking', desc: 'Detect hibernating apex predators.' },
      { lvl: 18, name: 'Camouflage Wrap', desc: 'Reduce beast aggro radius by 2 tiles.' },
      { lvl: 20, name: 'Heavy Bronze Harpoon', desc: 'Wield armor-piercing cast bronze harpoons.' },
      { lvl: 22, name: 'Crippling Strike', desc: 'Slow enemy movement speed by 50% for 4 ticks.' },
      { lvl: 24, name: 'Beast Pheromones II', desc: 'Lure pack alphas and rare variant beasts.' },
      { lvl: 26, name: 'Silent Hunter', desc: 'Gain +20% damage on the first strike from stealth.' },
      { lvl: 28, name: 'Terror Bird Lure', desc: 'Extract and use avian nesting bait.' },
      { lvl: 30, name: 'Obsidian War Javelin', desc: 'Throw razor-sharp volcanic glass javelins.' },
      { lvl: 32, name: 'Multi-Target Snare', desc: 'Root up to 2 adjacent beasts simultaneously.' },
      { lvl: 35, name: 'Apex Predator Instinct', desc: '+10% critical strike chance on wounded beasts.' },
      { lvl: 38, name: 'Mammoth Heart Shot', desc: 'Execute strike doing double damage below 20% HP.' },
      { lvl: 40, name: 'Starfall Bow Mastery', desc: 'Wield celestial meteorite alloy bows.' },
      { lvl: 42, name: 'Beast Empathy', desc: 'Pacify aggressive beasts for 10 seconds.' },
      { lvl: 44, name: 'Rainforest Pathfinder', desc: 'No movement penalty through dense foliage.' },
      { lvl: 46, name: 'Colossus Hunter', desc: '+25% damage against raid bosses and giants.' },
      { lvl: 48, name: 'Phantom Volley', desc: 'Fire 3 spectral spears in rapid succession.' },
      { lvl: 50, name: 'Grandmaster Hunt Master', desc: 'Unlock the mythical Starfall Hunter title & aura.' }
    ]
  },
  strength: {
    id: 'strength',
    name: 'Strength',
    icon: '💪',
    category: 'Combat',
    description: 'Raw muscle, heavy weapon impact, boulder throwing, and maximum melee damage.',
    unlocks: [
      { lvl: 1, name: 'Brawn I', desc: 'Base melee max hit increased.' },
      { lvl: 3, name: 'Heavy Club Grip', desc: 'Wield dense hardwood war clubs.' },
      { lvl: 5, name: 'Crushing Blow I', desc: 'Chance to ignore 10% of target defense.' },
      { lvl: 8, name: 'Basalt Boulder Lift', desc: 'Clear medium stone obstacles on trails.' },
      { lvl: 10, name: 'Bronze Greataxe', desc: 'Wield two-handed cast bronze greataxes.' },
      { lvl: 12, name: 'Muscle Memory', desc: '+5% attack speed with two-handed weapons.' },
      { lvl: 15, name: 'Ground Slam', desc: 'Stun adjacent enemies for 1 tick.' },
      { lvl: 18, name: 'Ironwood Sledge', desc: 'Wield heavy construction and battle sledges.' },
      { lvl: 20, name: 'Crushing Blow II', desc: 'Ignore 20% of target armor rating.' },
      { lvl: 22, name: 'Titan Grip', desc: 'Wield heavy two-handed axes in one hand with shield.' },
      { lvl: 25, name: 'Berserker Surge', desc: '+20% Strength when HP drops below 30%.' },
      { lvl: 28, name: 'Megalith Throw', desc: 'Hurl massive stones at range for heavy blunt damage.' },
      { lvl: 30, name: 'Obsidian War Maul', desc: 'Wield devastating volcanic obsidian mauls.' },
      { lvl: 32, name: 'Unstoppable Momentum', desc: 'Immunity to knockbacks and movement slows.' },
      { lvl: 35, name: 'Colossus Cleave', desc: 'Melee swings hit all enemies in a 180-degree arc.' },
      { lvl: 38, name: 'Bone Crusher', desc: 'Shatter monster defenses permanently in battle.' },
      { lvl: 40, name: 'Starfall War Hammer', desc: 'Wield celestial starfall alloy war hammers.' },
      { lvl: 42, name: 'Mountain Breaker', desc: 'Deal +35% damage against golems and stone foes.' },
      { lvl: 44, name: 'Primal Roar', desc: 'Intimidate enemies, reducing their attack by 15%.' },
      { lvl: 46, name: 'Titan Force', desc: '+10 to all maximum melee damage rolls.' },
      { lvl: 47, name: 'Endurance of the Mammoth', desc: 'Carry double inventory weight with no speed loss.' },
      { lvl: 48, name: 'Earth Shatter', desc: 'Crack the ground, dealing AoE seismic shockwaves.' },
      { lvl: 49, name: 'Overpower', desc: 'Execute strikes cannot be blocked or dodged.' },
      { lvl: 50, name: 'Titan of the Bronze Age', desc: 'Unlock the Titan Champion mantle & legendary aura.' },
      { lvl: 50, name: 'Mastery: Primal Strength', desc: 'Permanently increases all physical damage by 10%.' }
    ]
  },
  defense: {
    id: 'defense',
    name: 'Defense',
    icon: '🛡️',
    category: 'Combat',
    description: 'Shield blocking, armor mitigation, parrying, and protective stances.',
    unlocks: [
      { lvl: 1, name: 'Hide Guard', desc: 'Equip cured animal hide armor.' },
      { lvl: 3, name: 'Wicker Shield', desc: 'Craft and wield woven wicker round shields.' },
      { lvl: 5, name: 'Shield Wall I', desc: '+5% chance to completely block physical strikes.' },
      { lvl: 8, name: 'Tough Skin', desc: 'Passive 5% reduction to all incoming damage.' },
      { lvl: 10, name: 'Bronze Cuirass', desc: 'Equip cast bronze breastplates and greaves.' },
      { lvl: 12, name: 'Parry Stance', desc: 'Counter-attack immediately upon blocking.' },
      { lvl: 15, name: 'Mammoth Carapace Vest', desc: 'Equip dense mammoth bone plated armor.' },
      { lvl: 18, name: 'Shield Bash', desc: 'Stun foes with a shield thrust.' },
      { lvl: 20, name: 'Arsenical Bronze Shield', desc: 'Wield reinforced heavy bronze tower shields.' },
      { lvl: 22, name: 'Deflection Stance', desc: 'Chance to reflect 25% of damage back at attacker.' },
      { lvl: 25, name: 'Iron Skin Mastery', desc: 'Base defense increased by +15%.' },
      { lvl: 28, name: 'Raptor Scale Coat', desc: 'Equip piercing-resistant raptor scale cuirass.' },
      { lvl: 30, name: 'Obsidian Plate Armor', desc: 'Equip heat and lava resistant obsidian armor.' },
      { lvl: 32, name: 'Unbreakable Guard', desc: 'Blocking prevents all status debuffs and bleeds.' },
      { lvl: 35, name: 'Guardian Totem Stance', desc: 'Absorb 30% of damage dealt to nearby allies.' },
      { lvl: 38, name: 'Mammoth Bone Citadel', desc: 'Equip full ancient mammoth juggernaut armor.' },
      { lvl: 40, name: 'Starfall Aegis Shield', desc: 'Wield celestial starfall tower shield.' },
      { lvl: 42, name: 'Spellward Skin', desc: 'Gain 25% magical and elemental resistance.' },
      { lvl: 44, name: 'Fortress Formation', desc: 'Defense doubled when standing in fortified zones.' },
      { lvl: 46, name: 'Colossus Bulwark', desc: 'Maximum block chance increased to 75%.' },
      { lvl: 47, name: 'Indomitable Will', desc: 'Survive fatal blows with 1 HP once every 5 minutes.' },
      { lvl: 48, name: 'Bastion of the Sun', desc: 'Radiate blinding light that causes foes to miss.' },
      { lvl: 49, name: 'Aegis of the Ancients', desc: 'Passive 20% total damage reduction.' },
      { lvl: 50, name: 'Immortal Bronze Sentinel', desc: 'Unlock Sentinel title and indestructible crest.' },
      { lvl: 50, name: 'Mastery: Unyielding Guard', desc: 'Complete immunity to critical hits.' }
    ]
  },
  hitpoints: {
    id: 'hitpoints',
    name: 'Hitpoints',
    icon: '❤️',
    category: 'Combat',
    description: 'Vitality, biological endurance, natural health regeneration, and life force.',
    unlocks: [
      { lvl: 1, name: 'Primal Vitality I', desc: 'Base HP established.' },
      { lvl: 3, name: 'Resting Recovery', desc: 'Recover HP 20% faster when seated at campfires.' },
      { lvl: 5, name: 'Bloodline Resilience', desc: 'Max HP +5.' },
      { lvl: 8, name: 'Natural Coagulation', desc: 'Halve the duration of bleeding effects.' },
      { lvl: 10, name: 'Hardened Organs', desc: 'Max HP +10.' },
      { lvl: 12, name: 'Second Wind I', desc: 'Regenerate 10% HP instantly when escaping combat.' },
      { lvl: 15, name: 'Vitality Surge', desc: 'Max HP +15.' },
      { lvl: 18, name: 'Venom Resistance', desc: 'Immunity to low-tier serpent toxins.' },
      { lvl: 20, name: 'Tundra Constitution', desc: 'Immune to cold freezing environments in North.' },
      { lvl: 22, name: 'Max HP +25', desc: 'Large boost to total survivability pool.' },
      { lvl: 25, name: 'Rapid Regeneration', desc: 'Passively regenerate 1 HP every 3 game ticks.' },
      { lvl: 28, name: 'Lava Acclimation', desc: 'Take 50% reduced environmental heat damage.' },
      { lvl: 30, name: 'Max HP +40', desc: 'Fortify life pool for deep dungeon exploration.' },
      { lvl: 32, name: 'Blood Essence Well', desc: 'Consuming roasted meats heals +3 extra HP.' },
      { lvl: 35, name: 'Survivor Adrenaline', desc: 'Movement speed increases by 25% under 25% HP.' },
      { lvl: 38, name: 'Max HP +60', desc: 'End-game vitality boost.' },
      { lvl: 40, name: 'Mammoth Life Force', desc: 'Regenerate HP during combat every 5 ticks.' },
      { lvl: 42, name: 'Purified Blood', desc: 'Complete immunity to all poisons and diseases.' },
      { lvl: 44, name: 'Max HP +80', desc: 'Enormous health pool for raid encounters.' },
      { lvl: 46, name: 'Soul Anchor', desc: 'HP cannot be reduced by more than 40% in one hit.' },
      { lvl: 47, name: 'Avatar of Vitality', desc: 'Health potions and healing items yield +50% potency.' },
      { lvl: 48, name: 'Primal Rebirth', desc: 'Instantly restore 50% HP upon reaching 0 HP (10m CD).' },
      { lvl: 49, name: 'Max HP +100', desc: 'Peak mortal constitution.' },
      { lvl: 50, name: 'Eternal Life Shaman', desc: 'Unlock Ancient Vitalist title and permanent vitality.' },
      { lvl: 50, name: 'Mastery: Primal Blood', desc: 'Permanent +25% total maximum HP.' }
    ]
  },
  shamanism: {
    id: 'shamanism',
    name: 'Shamanism',
    icon: '🔮',
    category: 'Magic',
    description: 'Ancestral spirit chanting, weather rituals, totems, and elemental evocations.',
    unlocks: [
      { lvl: 1, name: 'Spirit Chant: Spark', desc: 'Evoke a crackling flame to light fires and strike.' },
      { lvl: 3, name: 'Ancestral Totem of Health', desc: 'Erect a totem that heals adjacent tribesmen.' },
      { lvl: 5, name: 'Gust of the Plains', desc: 'Ranged wind gust pushing back melee attackers.' },
      { lvl: 8, name: 'Spirit Sight', desc: 'Reveal hidden archaeological caches and spirits.' },
      { lvl: 10, name: 'Lightning Call I', desc: 'Strike an enemy with a bolt of sky lightning.' },
      { lvl: 12, name: 'Totem of Warding', desc: 'Totem granting +10 Defense to the tribe.' },
      { lvl: 15, name: 'Flame Ritual', desc: 'Ignite all enemies in a 3x3 tile area.' },
      { lvl: 18, name: 'Ghost Wolf Familiar', desc: 'Summon a spirit wolf to fight alongside you.' },
      { lvl: 20, name: 'Rain Dance Ritual', desc: 'Summon torrential rain to bless crops and soothe heat.' },
      { lvl: 22, name: 'Totem of Strength', desc: 'Totem granting +15% melee damage.' },
      { lvl: 25, name: 'Chain Lightning', desc: 'Lightning leaps between up to 4 enemy targets.' },
      { lvl: 28, name: 'Ancestral Shield', desc: 'Form a spirit bubble absorbing up to 50 damage.' },
      { lvl: 30, name: 'Earthquake Churn', desc: 'Fissure the ground, dealing heavy earth magic damage.' },
      { lvl: 32, name: 'Totem of Frenzy', desc: 'Totem increasing tribal attack speed by 25%.' },
      { lvl: 35, name: 'Call of the Sunken Gods', desc: 'Summon tentacles from subterranean rifts.' },
      { lvl: 38, name: 'Soul Siphon', desc: 'Drain HP from foes to heal your tribal allies.' },
      { lvl: 40, name: 'Eclipse Invocation', desc: 'Darken the skies, blinding enemies for 8 ticks.' },
      { lvl: 42, name: 'Grand Totem of the Elements', desc: 'Erect a master multi-elemental totem.' },
      { lvl: 44, name: 'Meteor Spirit Strike', desc: 'Call down celestial debris upon enemy hordes.' },
      { lvl: 46, name: 'Spirit Form Walk', desc: 'Become ethereal, passing through monsters and obstacles.' },
      { lvl: 47, name: 'Thunder God Avatar', desc: 'Transform into a storm avatar with rapid casting.' },
      { lvl: 48, name: 'Ancestral Resurrection', desc: 'Revive fallen allies on the battlefield.' },
      { lvl: 49, name: 'Wrath of the Earth Mother', desc: 'Cataclysmic AoE strike dealing massive magic damage.' },
      { lvl: 50, name: 'High Arch-Shaman of PRIMA', desc: 'Unlock High Shaman mantle and celestial glow.' },
      { lvl: 50, name: 'Mastery: Spirit Conduit', desc: 'Spirit energy regenerates 100% faster.' }
    ]
  },
  knapping: {
    id: 'knapping',
    name: 'Knapping',
    icon: '🪨',
    category: 'Crafting',
    description: 'Chipping flint, shaping obsidian blades, carving bone needles, and stone tools.',
    unlocks: [
      { lvl: 1, name: 'Flint Flake Knife', desc: 'Shape sharp flint scrapers and skinning knives.' },
      { lvl: 3, name: 'Flint Spearhead', desc: 'Knap pointed spearheads for hunting weapons.' },
      { lvl: 5, name: 'Flint Handaxe', desc: 'Chip sturdy stone axes for woodcutting.' },
      { lvl: 8, name: 'Bone Needles & Awls', desc: 'Fashion bone tools for leathercrafting.' },
      { lvl: 10, name: 'Obsidian Razor Blade', desc: 'Shape ultra-sharp volcanic glass scalpels.' },
      { lvl: 12, name: 'Flint Pickaxe Head', desc: 'Craft durable stone pickaxe heads for mining.' },
      { lvl: 15, name: 'Obsidian Arrowheads', desc: 'Knap precision obsidian projectile points.' },
      { lvl: 18, name: 'Polished Basalt Hammer', desc: 'Shape heavy stone forging hammers.' },
      { lvl: 20, name: 'Obsidian Dagger Core', desc: 'Craft ceremonial and ritual obsidian daggers.' },
      { lvl: 22, name: 'Runestone Chisel', desc: 'Craft fine chisels for masonry and tablet carving.' },
      { lvl: 25, name: 'Fine Micro-blades', desc: 'Produce interchangeable composite tool inserts.' },
      { lvl: 28, name: 'Obsidian War Scythe Blade', desc: 'Knap wide curved blades for war scythes.' },
      { lvl: 30, name: 'Starfall Chipping', desc: 'Shape raw meteorite fragments into sharp tools.' },
      { lvl: 32, name: 'Obsidian Greatsword Edge', desc: 'Attach razor-sharp obsidian edges to hardwood.' },
      { lvl: 35, name: 'Master Stone Carver Tools', desc: 'Craft legendary tier stoneworking instruments.' },
      { lvl: 38, name: 'Starfall Spearhead', desc: 'Chip celestial meteorite points with +40 bonus.' },
      { lvl: 40, name: 'Volcanic Glass Armor Plates', desc: 'Knap interlocking obsidian scales for armors.' },
      { lvl: 42, name: 'Diamond Core Chisels', desc: 'Extract and shape hardest gemstone tools.' },
      { lvl: 44, name: 'God-Slayer Javelin Tip', desc: 'Knap legendary tier projectile points.' },
      { lvl: 46, name: 'Flawless Pressure Flaking', desc: 'Stone tools never lose durability or sharpness.' },
      { lvl: 47, name: 'Celestial Runestone Matrix', desc: 'Carve mystical energy conduits into stones.' },
      { lvl: 48, name: 'Starfall Master Core', desc: 'Shape pure meteorite into divine weaponry.' },
      { lvl: 49, name: 'Primordial Razor Edge', desc: 'Knapped weapons gain permanent 15% bleed chance.' },
      { lvl: 50, name: 'Grandmaster Knapper of PRIMA', desc: 'Unlock Master Lapidary title and golden chisel.' },
      { lvl: 50, name: 'Mastery: Instant Flaking', desc: 'Craft all stone tools instantly with zero wait.' }
    ]
  },
  casting: {
    id: 'casting',
    name: 'Casting',
    icon: '🔥',
    category: 'Crafting',
    description: 'Crucible smelting, alloy metallurgy, lost-wax casting, and bronze weaponry.',
    unlocks: [
      { lvl: 1, name: 'Native Copper Smelting', desc: 'Smelt raw copper ore into copper ingots.' },
      { lvl: 3, name: 'Clay Mold Making', desc: 'Fashion reusable clay molds for simple tools.' },
      { lvl: 5, name: 'Copper Knife & Adze', desc: 'Cast copper work knives and wood chisels.' },
      { lvl: 8, name: 'Tin Ore Refining', desc: 'Refine cassiterite tin in low-temperature hearths.' },
      { lvl: 10, name: 'Classic Bronze Ingot', desc: 'Smelt 1x Copper + 1x Tin into Bronze Ingots.' },
      { lvl: 12, name: 'Cast Bronze Axe', desc: 'Forge bronze axes with high woodcutting power.' },
      { lvl: 15, name: 'Cast Bronze Spear', desc: 'Cast bronze spearheads with +14 attack bonus.' },
      { lvl: 18, name: 'Lost-Wax Casting Technique', desc: 'Produce intricate bronze armor decorations.' },
      { lvl: 20, name: 'Arsenical Bronze Ingot', desc: 'Smelt hardened toxic arsenical bronze alloys.' },
      { lvl: 22, name: 'Bronze Cuirass & Greaves', desc: 'Cast heavy bronze torso and leg armor plates.' },
      { lvl: 25, name: 'Cast Bronze Sword', desc: 'Forge the iconic leaf-bladed bronze sword.' },
      { lvl: 28, name: 'Bronze Helmet & Crest', desc: 'Cast reinforced bronze horned war helmets.' },
      { lvl: 30, name: 'Bismuth Bronze Alloy', desc: 'Smelt flexible and mirror-finish bronze alloys.' },
      { lvl: 32, name: 'Heavy Bronze War Hammer', desc: 'Cast massive bronze blunt crushing weapons.' },
      { lvl: 35, name: 'Crucible Heat Mastery', desc: 'Reduce fuel and coal requirements by 50%.' },
      { lvl: 38, name: 'High-Tin Mirrored Bronze', desc: 'Produce reflective bronze shields with spell ward.' },
      { lvl: 40, name: 'Starfall Alloy Smelting', desc: 'Smelt celestial meteorite into Starfall Alloy.' },
      { lvl: 42, name: 'Starfall God-Sword', desc: 'Cast legendary leaf-blade sword (+95 attack).' },
      { lvl: 44, name: 'Starfall Cuirass', desc: 'Cast celestial cuirass with +50 defense bonus.' },
      { lvl: 46, name: 'Perpetual Blast Furnace', desc: 'Smelt up to 10 ingots in a single tick.' },
      { lvl: 47, name: 'Volcanic Core Crucible', desc: 'Harness magma heat to forge indestructible alloys.' },
      { lvl: 48, name: 'Imperial Bronze Regalia', desc: 'Cast emperor tier coronation armor and weapons.' },
      { lvl: 49, name: 'Divine Metallurgy', desc: 'All cast weapons have chance to roll +15% extra stats.' },
      { lvl: 50, name: 'High Metallurgist of PRIMA', desc: 'Unlock Master Foundry title and golden crucible.' },
      { lvl: 50, name: 'Mastery: Alloy Resonance', desc: 'Forged gear grants +10% bonus damage/defense.' }
    ]
  },
  woodcutting: {
    id: 'woodcutting',
    name: 'Woodcutting',
    icon: '🪓',
    category: 'Gathering',
    description: 'Felling ancient palms, primeval cycads, dense ironwoods, and giant briar pines.',
    unlocks: [
      { lvl: 1, name: 'Cycad Palm Harvesting', desc: 'Chop fibrous cycad palm trees for soft timber.' },
      { lvl: 3, name: 'Bark Stripping', desc: 'Extract fibrous bark for cordage and rope.' },
      { lvl: 5, name: 'River Willow Chopping', desc: 'Harvest flexible willow branches for bows and rafts.' },
      { lvl: 8, name: 'Resin Tapping', desc: 'Extract flammable tree sap and adhesive pitch.' },
      { lvl: 10, name: 'Savannah Acacia Felling', desc: 'Chop dense acacia timber in the grasslands.' },
      { lvl: 12, name: 'Fast Chop I', desc: '+10% chance to harvest two logs from one tree.' },
      { lvl: 15, name: 'Bristlecone Pine', desc: 'Chop ancient mountain pines in the frost highlands.' },
      { lvl: 18, name: 'Hardwood Splitting', desc: 'Craft durable construction planks.' },
      { lvl: 20, name: 'Primeval Ironwood Felling', desc: 'Chop dense ironwood trees in the rainforest.' },
      { lvl: 22, name: 'Tree Felling Mastery I', desc: 'Reduce tree chop time by 1 tick.' },
      { lvl: 25, name: 'Ebony Swamp Timber', desc: 'Harvest rot-resistant dark swamp hardwoods.' },
      { lvl: 28, name: 'Lumberjack Strength', desc: 'Passively gain +5 Strength while woodcutting.' },
      { lvl: 30, name: 'Volcanic Ashwood Chopping', desc: 'Harvest heat-resistant ashwood near crags.' },
      { lvl: 32, name: 'Fast Chop II', desc: '+20% chance to harvest double logs.' },
      { lvl: 35, name: 'Ancient Mammoth Cypress', desc: 'Fell colossal cypress trees on northern steppes.' },
      { lvl: 38, name: 'Rare Amber Extraction', desc: 'Find precious amber gems inside tree trunks.' },
      { lvl: 40, name: 'Starfall Briar Tree', desc: 'Chop celestial briar trees infused with starfall.' },
      { lvl: 42, name: 'Forest Whisperer', desc: 'Tree respawn times reduced by 50% around you.' },
      { lvl: 44, name: 'World-Tree Branch Chopping', desc: 'Harvest mystical branches from sacred groves.' },
      { lvl: 46, name: 'One-Swing Felling', desc: 'Chance to fell an entire tree in a single swing.' },
      { lvl: 47, name: 'Evergreen Blessing', desc: 'Wood harvested never decays or rots.' },
      { lvl: 48, name: 'Colossal Timber Transport', desc: 'Auto-store chopped logs directly to tribal bank.' },
      { lvl: 49, name: 'Spirit of the Forest', desc: 'Chop trees with spectral bronze energy.' },
      { lvl: 50, name: 'Grand Forester of PRIMA', desc: 'Unlock High Lumberjack title and mythic axe.' },
      { lvl: 50, name: 'Mastery: Forest Lord', desc: 'Woodcutting yield doubled across all biomes.' }
    ]
  },
  foraging: {
    id: 'foraging',
    name: 'Foraging',
    icon: '🌿',
    category: 'Gathering',
    description: 'Gathering wild tubers, medicinal moss, glowing fungi, berries, and clay.',
    unlocks: [
      { lvl: 1, name: 'River Clay Lumps', desc: 'Gather rich sculpting and crucible clay from banks.' },
      { lvl: 3, name: 'Sweet Prairie Berries', desc: 'Forage vitamin-rich wild berries for food and dyes.' },
      { lvl: 5, name: 'Medicinal Fever Root', desc: 'Gather antiseptic fever roots for tribal healing.' },
      { lvl: 8, name: 'River Reed Cordage', desc: 'Harvest sturdy reeds for mats, rafts, and traps.' },
      { lvl: 10, name: 'Cave Glow Fungus', desc: 'Gather bioluminescent mushrooms for lanterns.' },
      { lvl: 12, name: 'Wild Wheat & Spelt', desc: 'Harvest primitive grain grains for flatbreads.' },
      { lvl: 15, name: 'Tundra Lichen & Moss', desc: 'Forage cold-weather insulation and wound moss.' },
      { lvl: 18, name: 'Serpent Vine', desc: 'Gather venomous climbing vines for alchemy poisons.' },
      { lvl: 20, name: 'Obsidian Sulfur Crystals', desc: 'Gather explosive sulfur deposits near rifts.' },
      { lvl: 22, name: 'Bountiful Forage I', desc: '+15% chance to gather double herbs and plants.' },
      { lvl: 25, name: 'Rainforest Ghost Orchid', desc: 'Gather rare orchid used in spirit potions.' },
      { lvl: 28, name: 'Highland Mountain Ginseng', desc: 'Forage stamina-boosting roots.' },
      { lvl: 30, name: 'Sunken Crypt Truffle', desc: 'Gather ancient fungal delicacies in crypts.' },
      { lvl: 32, name: 'Botanical Eye', desc: 'Highlight all forageable nodes on the minimap.' },
      { lvl: 35, name: 'Starfall Spore Cluster', desc: 'Gather extraterrestrial spores in crater.' },
      { lvl: 38, name: 'Ancestral Lotus Flower', desc: 'Forage sacred water lilies that restore spirit.' },
      { lvl: 40, name: 'Golden Honeycomb', desc: 'Harvest wild giant bee honey for elixirs.' },
      { lvl: 42, name: 'Bountiful Forage II', desc: '+30% chance for triple gather yields.' },
      { lvl: 44, name: 'Primordial Mandrake', desc: 'Harvest magical screaming mandrake roots.' },
      { lvl: 46, name: 'Nature’s Bounty Aura', desc: 'Herbs gathered grant temporary health regeneration.' },
      { lvl: 47, name: 'Fossilized Seed Extraction', desc: 'Extract extinct prehistoric seeds for planting.' },
      { lvl: 48, name: 'Celestial Herbology', desc: 'Gather herbs infused with starfall magic.' },
      { lvl: 49, name: 'Infinite Harvest', desc: 'Resource nodes never deplete when gathered by you.' },
      { lvl: 50, name: 'Grand Herbalist of PRIMA', desc: 'Unlock Master Botanist title and herbalist cloak.' },
      { lvl: 50, name: 'Mastery: Earth Whisper', desc: 'Triple XP and yield on all gathered botanicals.' }
    ]
  },
  cooking: {
    id: 'cooking',
    name: 'Cooking',
    icon: '🍖',
    category: 'Crafting',
    description: 'Campfire roasting, clay pot stewing, meat smoking, and restorative feasts.',
    unlocks: [
      { lvl: 1, name: 'Roasted Boar Meat', desc: 'Cook raw boar meat on campfires (heals 6 HP).' },
      { lvl: 3, name: 'Smoked River Fish', desc: 'Smoke freshwater catch to prevent spoiling.' },
      { lvl: 5, name: 'Clay Pot Porridge', desc: 'Stew wild grains with water for stamina food.' },
      { lvl: 8, name: 'Wild Berry Tart', desc: 'Bake sweet berry cakes in hot stone hearths.' },
      { lvl: 10, name: 'Roasted Dire Wolf Flank', desc: 'Cook savory wolf meat (heals 10 HP).' },
      { lvl: 12, name: 'Campfire Efficiency I', desc: 'Burn chance reduced by 50% on all recipes.' },
      { lvl: 15, name: 'Raptor Egg Omelet', desc: 'Cook nutritious raptor eggs with prairie herbs.' },
      { lvl: 18, name: 'Highland Venison Roast', desc: 'Roast tender deer meat with wild garlic.' },
      { lvl: 20, name: 'Mammoth Tenderloin Steak', desc: 'Cook hearty mammoth steak (heals 18 HP).' },
      { lvl: 22, name: 'Herbal Meat Skewers', desc: 'Combine meat + fever root to heal and cure poison.' },
      { lvl: 25, name: 'Savannah Spiced Stew', desc: 'Simmer rich bone broth in large clay cauldrons.' },
      { lvl: 28, name: 'Smoked Salmon Jerky', desc: 'High-stamina travel rations (stackable food).' },
      { lvl: 30, name: 'Cave Bear Ribs', desc: 'Roast enormous apex predator ribs (heals 24 HP).' },
      { lvl: 32, name: 'Campfire Efficiency II', desc: 'Zero food burn rate on all traditional meats.' },
      { lvl: 35, name: 'Primeval Honey Glazed Meat', desc: 'Boost max HP by +10 for 10 minutes.' },
      { lvl: 38, name: 'Deep Abyss Kraken Chowder', desc: 'Cook exotic seafood stew (heals 32 HP).' },
      { lvl: 40, name: 'Starfall Roast', desc: 'Cook starfall-infused meats granting energy glow.' },
      { lvl: 42, name: 'Feast of the Great Chieftain', desc: 'Cook tribal table feast healing all nearby allies.' },
      { lvl: 44, name: 'Dragon Drake Tail Steak', desc: 'Roast fire-infused drake meat (heals 42 HP).' },
      { lvl: 46, name: 'Master Chef Speed', desc: 'Cook an entire inventory of 28 foods in 1 tick.' },
      { lvl: 47, name: 'Elixir of the Ever-Full', desc: 'Cook meals that restore both HP and Spirit.' },
      { lvl: 48, name: 'Ambrosia of the Sun', desc: 'Brew divine honey-wine restoring full stats.' },
      { lvl: 49, name: 'Titan Feast', desc: 'Cook colossal banquet granting +20% damage buff.' },
      { lvl: 50, name: 'Grandmaster Chef of PRIMA', desc: 'Unlock Grand Feastmaster title and golden spit.' },
      { lvl: 50, name: 'Mastery: Gourmet Touch', desc: 'All prepared food heals +30% additional HP.' }
    ]
  },
  leatherworking: {
    id: 'leatherworking',
    name: 'Leatherworking',
    icon: '🧥',
    category: 'Crafting',
    description: 'Tanning beast pelts, sewing leather tunics, crafting raptor scale vests.',
    unlocks: [
      { lvl: 1, name: 'Wolf Pelt Tanning', desc: 'Tan raw wolf pelts using brain-tanning methods.' },
      { lvl: 3, name: 'Leather Footwraps', desc: 'Stitch soft leather boots increasing run speed.' },
      { lvl: 5, name: 'Rawhide Quiver', desc: 'Craft quivers holding up to 50 arrows or spears.' },
      { lvl: 8, name: 'Studded Leather Bracers', desc: 'Reinforce leather cuffs with bone studs.' },
      { lvl: 10, name: 'Cured Mammoth Hide Tunic', desc: 'Craft thick cold-resistant mammoth body armor.' },
      { lvl: 12, name: 'Leather Waterskin', desc: 'Sew durable waterskins for desert travel.' },
      { lvl: 15, name: 'Raptor Scale Vest', desc: 'Stitch lightweight reptile scale chestplates.' },
      { lvl: 18, name: 'Beast Master Belt', desc: 'Craft utility belt adding +2 quick-action slots.' },
      { lvl: 20, name: 'Hardened Leather Cuirass', desc: 'Boil leather in wax for rigid breastplates.' },
      { lvl: 22, name: 'Cave Bear Fur Cloak', desc: 'Sew heavy fur cape granting frost immunity.' },
      { lvl: 25, name: 'Reinforced Raptor Gauntlets', desc: 'Craft claw-tipped leather combat gloves.' },
      { lvl: 28, name: 'Tanned Basilisk Hide', desc: 'Tan acid-resistant reptile leathers.' },
      { lvl: 30, name: 'Mammoth Juggernaut Harness', desc: 'Craft mount saddle and beast armor harness.' },
      { lvl: 32, name: 'Master Stitching I', desc: '+15% armor rating on all crafted leather gear.' },
      { lvl: 35, name: 'Shadow Stalker Leathers', desc: 'Craft stealth leathers reducing enemy detection.' },
      { lvl: 38, name: 'Deep Serpent Scale Mail', desc: 'Craft water-breathing serpent scale armors.' },
      { lvl: 40, name: 'Starfall Infused Hide', desc: 'Tan pelts treated with glowing celestial dust.' },
      { lvl: 42, name: 'Fire Drake Scale Cuirass', desc: 'Craft fireproof dragon leather armor.' },
      { lvl: 44, name: 'Titan Beast Backpack', desc: 'Expand tribal inventory capacity.' },
      { lvl: 46, name: 'Master Stitching II', desc: 'Chance to craft double items with zero hide loss.' },
      { lvl: 47, name: 'Ghost Beast Cloak', desc: 'Sew camouflage cloak granting invisibility.' },
      { lvl: 48, name: 'Crown of the Mammoth Lord', desc: 'Craft legendary tusk-adorned leather headdress.' },
      { lvl: 49, name: 'Impervious Hide Armor', desc: 'All crafted leathers gain +25 physical defense.' },
      { lvl: 50, name: 'Grand Tanner of PRIMA', desc: 'Unlock Master Furrier title and mythical awl.' },
      { lvl: 50, name: 'Mastery: Primal Weave', desc: 'Crafted armors grant +10% maximum movement speed.' }
    ]
  },
  masonry: {
    id: 'masonry',
    name: 'Masonry',
    icon: '🏛️',
    category: 'Crafting',
    description: 'Carving stone megaliths, erecting boundary steles, building fortified stone hearths.',
    unlocks: [
      { lvl: 1, name: 'Cobblestone Paving', desc: 'Lay stone paths increasing walking speed.' },
      { lvl: 3, name: 'Stone Fire Ring', desc: 'Build permanent campfires that burn indefinitely.' },
      { lvl: 5, name: 'Clay Brick Molding', desc: 'Bake mud bricks for settlement buildings.' },
      { lvl: 8, name: 'Basalt Shaping Anvil', desc: 'Construct heavy stone crafting anvils.' },
      { lvl: 10, name: 'Tribal Boundary Stele', desc: 'Carve territory markers warding off monsters.' },
      { lvl: 12, name: 'Megalith Quarrying', desc: 'Extract 10-ton granite blocks from cliffs.' },
      { lvl: 15, name: 'Sunken Crypt Sarcophagus', desc: 'Carve sealed stone burial crypts.' },
      { lvl: 18, name: 'Stone Watchtower Base', desc: 'Erect elevated stone observation towers.' },
      { lvl: 20, name: 'Totem Megalith Pedestal', desc: 'Carve glowing rune bases for shaman totems.' },
      { lvl: 22, name: 'Fortified Stone Walls', desc: 'Construct defensive perimeter walls around camps.' },
      { lvl: 25, name: 'Obsidian Monolith', desc: 'Erect towering obsidian obelisks that channel heat.' },
      { lvl: 28, name: 'Aqueduct Channelling', desc: 'Carve stone water canals to irrigate oases.' },
      { lvl: 30, name: 'Ancient Stone Archway', desc: 'Build grand city entrance gates.' },
      { lvl: 32, name: 'Megalith Transport Harness', desc: 'Move massive stones over logs with ease.' },
      { lvl: 35, name: 'Sun Temple Foundation', desc: 'Construct astronomical stone alignment rings.' },
      { lvl: 38, name: 'Colossus Statue Carving', desc: 'Carve giant guardian statues in settlements.' },
      { lvl: 40, name: 'Starfall Inlaid Obelisk', desc: 'Embed meteorite crystals into stone monuments.' },
      { lvl: 42, name: 'Indestructible Fortress Gate', desc: 'Build gates resistant to all siege damage.' },
      { lvl: 44, name: 'Pyramid Megalith Step', desc: 'Construct towering stepped stone monuments.' },
      { lvl: 46, name: 'Instant Stone Setting', desc: 'Erect stone structures in half the required time.' },
      { lvl: 47, name: 'Runic Fortress Wards', desc: 'Inscribed walls zap attacking enemies with lightning.' },
      { lvl: 48, name: 'Monument to the First Dynasty', desc: 'Build world-wonder tier tribal monuments.' },
      { lvl: 49, name: 'Titan Stone Golem Shell', desc: 'Carve autonomous stone golem armor shells.' },
      { lvl: 50, name: 'Grand Mason of PRIMA', desc: 'Unlock Master Architect title and stone crown.' },
      { lvl: 50, name: 'Mastery: Eternal Stone', desc: 'All crafted stone buildings have infinite durability.' }
    ]
  },
  fishing: {
    id: 'fishing',
    name: 'Fishing',
    icon: '🐟',
    category: 'Gathering',
    description: 'Harpooning river salmon, setting fish weirs, catching giant lake sturgeon.',
    unlocks: [
      { lvl: 1, name: 'River Salmon Harpooning', desc: 'Harpoon freshwater salmon from shallow streams.' },
      { lvl: 3, name: 'Bone Fishhooks', desc: 'Craft bone fishhooks for line fishing in lakes.' },
      { lvl: 5, name: 'Wicker Fish Weir', desc: 'Deploy stationary wicker fish traps in river fords.' },
      { lvl: 8, name: 'Speckled Trout Catching', desc: 'Catch fast-swimming mountain stream trout.' },
      { lvl: 10, name: 'Freshwater Crayfish Pot', desc: 'Catch mud crayfish in riverbanks.' },
      { lvl: 12, name: 'Fast Reel I', desc: '+10% fishing speed in all water zones.' },
      { lvl: 15, name: 'Great Lake Sturgeon', desc: 'Harpoon giant prehistoric armored sturgeon.' },
      { lvl: 18, name: 'River Eel Trapping', desc: 'Catch electric and river eels in muddy swamps.' },
      { lvl: 20, name: 'Bronze Harpoon Mastery', desc: 'Harpoon heavy deep-water fish with ease.' },
      { lvl: 22, name: 'Bait Crafting: Insect Lure', desc: 'Attract rare fish species using crafted lures.' },
      { lvl: 25, name: 'Rainforest Giant Arapaima', desc: 'Catch massive apex freshwater fish.' },
      { lvl: 28, name: 'Double Catch I', desc: '+15% chance to catch two fish simultaneously.' },
      { lvl: 30, name: 'Volcanic Magma Eel', desc: 'Catch heat-resistant eels in subterranean rifts.' },
      { lvl: 32, name: 'Tundra Ice Fishing', desc: 'Drill ice holes to catch arctic char in the north.' },
      { lvl: 35, name: 'Deep Abyss River Leviathan', desc: 'Hook legendary river serpents in the abyss.' },
      { lvl: 38, name: 'Rare Pearl Extraction', desc: 'Harvest precious freshwater pearls inside clams.' },
      { lvl: 40, name: 'Starfall Lure Fishing', desc: 'Use glowing celestial bait to attract sky-fish.' },
      { lvl: 42, name: 'Primeval Kraken Harpooning', desc: 'Harpoon multi-tentacled river raid bosses.' },
      { lvl: 44, name: 'Master Net Casting', desc: 'Haul entire schools of fish in a single throw.' },
      { lvl: 46, name: 'Fast Reel II', desc: 'Fishing catch rate increased by +35%.' },
      { lvl: 47, name: 'Ghost Water Angling', desc: 'Catch spiritual fish that restore spirit energy.' },
      { lvl: 48, name: 'Leviathan Whisperer', desc: 'Summon aquatic mounts from deep riverbeds.' },
      { lvl: 49, name: 'Infinite School', desc: 'Fishing spots never deplete while you fish.' },
      { lvl: 50, name: 'Grand Angler of PRIMA', desc: 'Unlock Master Waterman title and golden harpoon.' },
      { lvl: 50, name: 'Mastery: Ocean King', desc: 'Double XP and catch yield across all waterways.' }
    ]
  },
  husbandry: {
    id: 'husbandry',
    name: 'Husbandry',
    icon: '🦣',
    category: 'Utility',
    description: 'Taming wild beasts, domesticating raptors, breeding woolly mammoths, mounts.',
    unlocks: [
      { lvl: 1, name: 'Wild Dire Wolf Pup Taming', desc: 'Bait and tame young dire wolf pups.' },
      { lvl: 3, name: 'Pack Handling I', desc: 'Control 1 active wolf companion in combat.' },
      { lvl: 5, name: 'Primitive Beast Whistle', desc: 'Call your tamed companion to your location.' },
      { lvl: 8, name: 'Animal Feed Formulation', desc: 'Craft nutrient-rich fodder to accelerate beast growth.' },
      { lvl: 10, name: 'Saber Raptor Domestication', desc: 'Tame swift bipedal hunting raptors.' },
      { lvl: 12, name: 'Raptor Saddle Crafting', desc: 'Equip saddles to ride raptors as swift mounts.' },
      { lvl: 15, name: 'Beast Armor Plating', desc: 'Attach bone armor to your animal companions.' },
      { lvl: 18, name: 'Pack Handling II', desc: 'Command 2 simultaneous wolf companions.' },
      { lvl: 20, name: 'Wild Boar Taming', desc: 'Domesticate hardy boars for camp defense and foraging.' },
      { lvl: 22, name: 'Beast Stance: Aggressive', desc: 'Companions deal +25% damage in combat.' },
      { lvl: 25, name: 'Cave Bear Domestication', desc: 'Tame colossal cave bears as heavy battle tanks.' },
      { lvl: 28, name: 'Selective Breeding I', desc: 'Breed beasts with inherited stat bonuses.' },
      { lvl: 30, name: 'Woolly Mammoth Taming', desc: 'Tame magnificent woolly mammoths as pack mounts.' },
      { lvl: 32, name: 'Mammoth Howdah Platform', desc: 'Mount archer platforms atop your woolly mammoth.' },
      { lvl: 35, name: 'Terror Bird Breeding', desc: 'Raise fast sprint mounts for messenger duties.' },
      { lvl: 38, name: 'Beast Revive Ritual', desc: 'Resurrect fallen companions without penalty.' },
      { lvl: 40, name: 'Starfall Beast Imprinting', desc: 'Breed celestial-patterned glow beasts.' },
      { lvl: 42, name: 'Alpha Beast Command', desc: 'Companions intimidate foes, reducing their attack.' },
      { lvl: 44, name: 'Fire Drake Domestication', desc: 'Tame winged volcanic drakes as flying mounts.' },
      { lvl: 46, name: 'Pack Handling III', desc: 'Lead an entire pack of 4 companion beasts.' },
      { lvl: 47, name: 'Titan Mammoth Mount', desc: 'Ride the ancient mammoth king into combat.' },
      { lvl: 48, name: 'Beast Link Telepathy', desc: 'Share health pools with your primary companion.' },
      { lvl: 49, name: 'Primal Swarm Mastery', desc: 'Summon all domesticated beasts in large raid battles.' },
      { lvl: 50, name: 'Grand Beastmaster of PRIMA', desc: 'Unlock Lord of Beasts title and mammoth horn.' },
      { lvl: 50, name: 'Mastery: Primal Bond', desc: 'All tamed mounts and pets gain +50% health.' }
    ]
  },
  archaeology: {
    id: 'archaeology',
    name: 'Archaeology',
    icon: '📜',
    category: 'Lore',
    description: 'Excavating ancient fossils, deciphering glyphs, uncovering precursor relics.',
    unlocks: [
      { lvl: 1, name: 'Fossil Extraction I', desc: 'Excavate trilobite and amber fossils from clay.' },
      { lvl: 3, name: 'Prehistoric Bone Cleaning', desc: 'Restore excavated bones for museum display.' },
      { lvl: 5, name: 'Glyph Deciphering I', desc: 'Translate simple tribal rock art inscriptions.' },
      { lvl: 8, name: 'Relic Preservation Resin', desc: 'Treat ancient wooden and leather artifacts.' },
      { lvl: 10, name: 'Sunken Crypt Excavation', desc: 'Dig into buried burial mounds and chambers.' },
      { lvl: 12, name: 'Fossil Identification', desc: 'Identify extinct beast skeletons for knowledge XP.' },
      { lvl: 15, name: 'Ancient Clay Tablet Reading', desc: 'Decipher early cuneiform trading tablets.' },
      { lvl: 18, name: 'Megalith Dowsing', desc: 'Locate buried stone ruins beneath the savannah.' },
      { lvl: 20, name: 'Starfall Crater Digging', desc: 'Excavate extraterrestrial impact artifacts.' },
      { lvl: 22, name: 'Archaeological Brush Mastery', desc: 'Uncover relics without damaging delicate layers.' },
      { lvl: 25, name: 'Precursor Power Conduit', desc: 'Restore ancient energy-conducting stone relics.' },
      { lvl: 28, name: 'Glyph Deciphering II', desc: 'Read complex astrological and shamanic seals.' },
      { lvl: 30, name: 'Obsidian Temple Excavation', desc: 'Unearth buried temples in volcanic rifts.' },
      { lvl: 32, name: 'Titan Skeleton Reconstruction', desc: 'Assemble complete 30-foot beast skeletons.' },
      { lvl: 35, name: 'Ancient Language Mastery', desc: 'Speak to ancient tomb spirits in their tongue.' },
      { lvl: 38, name: 'Relic Overcharge', desc: 'Temporarily empower relics for combat buffs.' },
      { lvl: 40, name: 'Vault of the Ancients Access', desc: 'Unlock sealed precursor archive vaults.' },
      { lvl: 42, name: 'Astral Tablet Synthesis', desc: 'Combine broken tablets to reveal hidden lore.' },
      { lvl: 44, name: 'Primeval God-Mask Restoration', desc: 'Restore legendary tribal shaman masks.' },
      { lvl: 46, name: 'Instant Excavation Scan', desc: 'Instantly reveal all buried relics in a 20-tile area.' },
      { lvl: 47, name: 'Precursor Technology Interface', desc: 'Operate ancient mechanical stone levers.' },
      { lvl: 48, name: 'Lost History of PRIMA', desc: 'Reconstruct the complete prehistoric timeline.' },
      { lvl: 49, name: 'Relic of the First Sun', desc: 'Excavate the mythic solar disk artifact.' },
      { lvl: 50, name: 'Grand Antiquarian of PRIMA', desc: 'Unlock Master Archaeologist title and relic staff.' },
      { lvl: 50, name: 'Mastery: Ancestral Wisdom', desc: 'All archaeological relic yields grant triple XP.' }
    ]
  },
  astronomy: {
    id: 'astronomy',
    name: 'Astronomy',
    icon: '✨',
    category: 'Lore',
    description: 'Charting constellations, predicting solar eclipses, starfall trajectory tracking.',
    unlocks: [
      { lvl: 1, name: 'Night Sky Navigation', desc: 'Navigate without minimap using the North Star.' },
      { lvl: 3, name: 'Sundial Crafting', desc: 'Craft portable bone sundials to tell exact server time.' },
      { lvl: 5, name: 'Solstice Observation', desc: 'Gain +10% gathering XP during midday solar peak.' },
      { lvl: 8, name: 'Moon Phase Tracking', desc: 'Predict full moon beast frenzy and spawn cycles.' },
      { lvl: 10, name: 'Star Stone Alignment', desc: 'Align stone steles with major constellations.' },
      { lvl: 12, name: 'Meteor Shower Prediction', desc: 'Predict when and where meteorite nodes will fall.' },
      { lvl: 15, name: 'Starlight Navigation', desc: 'Movement speed increased by 15% during night cycles.' },
      { lvl: 18, name: 'Astrolabe of Bone & Bronze', desc: 'Craft precision celestial measurement tools.' },
      { lvl: 20, name: 'Solar Flare Divination', desc: 'Harvest solar energy to charge shamanic totems.' },
      { lvl: 22, name: 'Eclipse Prediction I', desc: 'Foresee solar eclipses and prepare for blood events.' },
      { lvl: 25, name: 'Constellation of the Mammoth', desc: 'Gain +10% Strength when the Mammoth Star rises.' },
      { lvl: 28, name: 'Starfall Core Detection', desc: 'Pinpoint underground starfall deposits on map.' },
      { lvl: 30, name: 'Constellation of the Raptor', desc: 'Gain +10% Hunting speed during Raptor Zenith.' },
      { lvl: 32, name: 'Celestial Prism Crafting', desc: 'Refract starlight into concentrated laser beams.' },
      { lvl: 35, name: 'Blood Moon Ritual Mastery', desc: 'Harness blood moon energy for combat surges.' },
      { lvl: 38, name: 'Constellation of the Golem', desc: 'Gain +15% Defense when the Golem Star ascends.' },
      { lvl: 40, name: 'Star Gate Alignment', desc: 'Activate ancient stone teleportation arches.' },
      { lvl: 42, name: 'Supernova Divination', desc: 'Call down bursts of celestial light in battles.' },
      { lvl: 44, name: 'Celestial Navigation Grid', desc: 'Teleport to any discovered city once per hour.' },
      { lvl: 46, name: 'Master of Equinoxes', desc: 'Seasonal bonuses doubled in all biomes.' },
      { lvl: 47, name: 'Starfall Magnetism', desc: 'Attract falling starfall ore directly to your bag.' },
      { lvl: 48, name: 'Avatar of the Cosmos', desc: 'Bathe in celestial light, immune to night debuffs.' },
      { lvl: 49, name: 'The Grand Alignment', desc: 'Trigger alignment buff: all skills gain +25% XP.' },
      { lvl: 50, name: 'High Stargazer of PRIMA', desc: 'Unlock Cosmic Archon title and starfall crown.' },
      { lvl: 50, name: 'Mastery: Celestial Harmony', desc: 'Permanent +10% critical strike across all skills.' }
    ]
  },
  bartering: {
    id: 'bartering',
    name: 'Bartering',
    icon: '🪙',
    category: 'Utility',
    description: 'Haggling prices, exchange fee reductions, trade routes, and merchant priority.',
    unlocks: [
      { lvl: 1, name: 'Amber Appraisal', desc: 'Verify the purity and authentic value of amber beads.' },
      { lvl: 3, name: 'Haggler I', desc: 'Reduce shop buy prices by 5% in tribal settlements.' },
      { lvl: 5, name: 'Grand Totem Order Slot +1', desc: 'Place up to 4 simultaneous exchange orders.' },
      { lvl: 8, name: 'Merchant Scales', desc: 'Accurately weigh bulk ore for fair trade deals.' },
      { lvl: 10, name: 'Exchange Tax Cut I', desc: 'Reduce Grand Totem Exchange tax from 2% to 1.5%.' },
      { lvl: 12, name: 'Bulk Trading I', desc: 'Buy and sell items in stacks of 100 with zero fee.' },
      { lvl: 15, name: 'Haggler II', desc: 'Sell items to NPC merchants for +10% higher amber.' },
      { lvl: 18, name: 'Grand Totem Order Slot +2', desc: 'Place up to 6 simultaneous exchange orders.' },
      { lvl: 20, name: 'Caravan Route Knowledge', desc: 'Fast-travel between trading cities for half cost.' },
      { lvl: 22, name: 'Exchange Tax Cut II', desc: 'Reduce Grand Totem Exchange tax to 1.0%.' },
      { lvl: 25, name: 'Market Speculator', desc: 'Inspect recent price trends and volume on exchange.' },
      { lvl: 28, name: 'Merchant Diplomat', desc: 'Unlock exclusive merchant guild goods in cities.' },
      { lvl: 30, name: 'Grand Totem Order Slot +4', desc: 'Place up to 10 simultaneous exchange orders.' },
      { lvl: 32, name: 'Exchange Tax Cut III', desc: 'Reduce Grand Totem Exchange tax to 0.5%.' },
      { lvl: 35, name: 'Tribal Bank Expansion +25', desc: 'Expand tribal vault by 25 additional slots.' },
      { lvl: 38, name: 'Bulk Trading II', desc: 'Execute trades in stacks of 1,000 items.' },
      { lvl: 40, name: 'High Merchant Priority', desc: 'Orders match with top priority in orderbook queue.' },
      { lvl: 42, name: 'Zero-Fee Trading Days', desc: 'Pay 0% tax on weekends and celestial holidays.' },
      { lvl: 44, name: 'Grand Totem Order Slot +6', desc: 'Place up to 16 simultaneous exchange orders.' },
      { lvl: 46, name: 'Tribal Bank Expansion +50', desc: 'Expand tribal vault to 100 total capacity.' },
      { lvl: 47, name: 'Royal Merchant Charter', desc: 'Found trade caravans that generate passive amber.' },
      { lvl: 48, name: 'Emperor of Trade', desc: 'Access VIP merchant auctions for rare NFT artifacts.' },
      { lvl: 49, name: 'Golden Touch', desc: 'Small chance for bartered goods to double in quantity.' },
      { lvl: 50, name: 'Grand Merchant Prince of PRIMA', desc: 'Unlock Merchant King title and golden coin purse.' },
      { lvl: 50, name: 'Mastery: Free Trade', desc: 'Permanent 0% exchange fees and infinite order limits.' }
    ]
  },
  alchemy: {
    id: 'alchemy',
    name: 'Alchemy',
    icon: '🧪',
    category: 'Crafting',
    description: 'Extracting serpent toxins, brewing berserker tonics, and medicinal salves.',
    unlocks: [
      { lvl: 1, name: 'Antiseptic Fever Poultice', desc: 'Brew topical salves that stop bleeding and heal.' },
      { lvl: 3, name: 'Vial Molding', desc: 'Bake clay and glass phials for potion storage.' },
      { lvl: 5, name: 'Serpent Toxin Extraction', desc: 'Extract venom from viper fangs to coat weapons.' },
      { lvl: 8, name: 'Stamina Tonic', desc: 'Brew herbal drink restoring 100% run stamina.' },
      { lvl: 10, name: 'Hunter Strength Brew', desc: 'Brew potion boosting Strength by +5 for 5 minutes.' },
      { lvl: 12, name: 'Antidote Elixir', desc: 'Neutralize all forms of poison and venom instantly.' },
      { lvl: 15, name: 'Berserker War Draught', desc: '+15% Attack and Strength, -5% Defense for 3m.' },
      { lvl: 18, name: 'Fire-Resistant Salve', desc: 'Grants 50% immunity to burn and lava damage.' },
      { lvl: 20, name: 'Spirit Surge Potion', desc: 'Restore 50% Spirit energy for shamanic casting.' },
      { lvl: 22, name: 'Night Eye Elixir', desc: 'See clearly in pitch black caves and night cycles.' },
      { lvl: 25, name: 'Super Strength Brew', desc: 'Boost Strength by +12 for 10 minutes.' },
      { lvl: 28, name: 'Raptor Speed Potion', desc: 'Increase base movement speed by 30% for 2m.' },
      { lvl: 30, name: 'Liquid Fire Flask', desc: 'Throwable potion that creates lasting flame field.' },
      { lvl: 32, name: 'Trophy Hunter Potion', desc: 'Boost drop rates of rare beast parts by 25%.' },
      { lvl: 35, name: 'Elixir of the Mammoth Juggernaut', desc: 'Gain +25 Defense and temporary +30 HP.' },
      { lvl: 38, name: 'Venom Master Blade Coating', desc: 'Weapons inflict lethal poison on every strike.' },
      { lvl: 40, name: 'Starfall Celestial Draught', desc: 'Boost all combat skills by +15 for 15 minutes.' },
      { lvl: 42, name: 'Elixir of Invisibility', desc: 'Turn completely invisible for 30 seconds.' },
      { lvl: 44, name: 'Phoenix Ash Restorative', desc: 'Auto-revive potion triggered upon lethal blow.' },
      { lvl: 46, name: 'Batch Brewing Mastery', desc: 'Brew up to 10 potions simultaneously in 1 tick.' },
      { lvl: 47, name: 'Philosopher’s Crucible', desc: 'Transmute lead ore into native copper and silver.' },
      { lvl: 48, name: 'Elixir of Immortality', desc: 'Immunity to all damage for 8 seconds (10m CD).' },
      { lvl: 49, name: 'Primal Panacea', desc: 'Instantly restore full HP, Spirit, and cleanse debuffs.' },
      { lvl: 50, name: 'Grand Alchemist of PRIMA', desc: 'Unlock Master Apothecary title and glowing vial.' },
      { lvl: 50, name: 'Mastery: Alchemical Mastery', desc: 'All potion durations doubled and potency +25%.' }
    ]
  },
  trapping: {
    id: 'trapping',
    name: 'Trapping',
    icon: '🪤',
    category: 'Gathering',
    description: 'Laying deadfalls, setting beast snares, pit traps, and capturing wild animals.',
    unlocks: [
      { lvl: 1, name: 'Reed Snare Net', desc: 'Set woven reed snares for prairie hares and fowl.' },
      { lvl: 3, name: 'Deadfall Trap', desc: 'Construct stone deadfalls for badger and fox pelts.' },
      { lvl: 5, name: 'Bait Selection I', desc: 'Increase trapping success rate by 15% with meat.' },
      { lvl: 8, name: 'Simultaneous Traps: 2', desc: 'Deploy up to 2 traps at the same time.' },
      { lvl: 10, name: 'Pitfall Spike Trap', desc: 'Dig camouflaged pitfall traps for dire wolves.' },
      { lvl: 12, name: 'Bone Jaw Trap', desc: 'Craft spring-loaded bone jaw traps.' },
      { lvl: 15, name: 'Simultaneous Traps: 3', desc: 'Deploy up to 3 active traps concurrently.' },
      { lvl: 18, name: 'Raptor Cage Trap', desc: 'Construct reinforced ironwood cages for live capture.' },
      { lvl: 20, name: 'Camouflage Trap Mastery I', desc: 'Traps trigger 25% faster when placed in foliage.' },
      { lvl: 22, name: 'Simultaneous Traps: 4', desc: 'Deploy up to 4 traps across the biome.' },
      { lvl: 25, name: 'Heavy Bronze Bear Trap', desc: 'Deploy bronze teeth traps holding massive beasts.' },
      { lvl: 28, name: 'Pheromone Trap Scent', desc: 'Lure rare variant beasts into traps from 20 tiles.' },
      { lvl: 30, name: 'Mammoth Pitfall Trench', desc: 'Excavate massive trenches for woolly mammoths.' },
      { lvl: 32, name: 'Simultaneous Traps: 5', desc: 'Deploy up to 5 traps concurrently.' },
      { lvl: 35, name: 'Electrified Shaman Snare', desc: 'Infuse snares with lightning magic.' },
      { lvl: 38, name: 'Instant Trap Reset', desc: 'Traps auto-reset themselves after triggering.' },
      { lvl: 40, name: 'Starfall Cage Net', desc: 'Trap celestial starfall creatures in craters.' },
      { lvl: 42, name: 'Simultaneous Traps: 6', desc: 'Deploy up to 6 traps across multiple biomes.' },
      { lvl: 44, name: 'Dragon Drake Snare', desc: 'Set heavy ground anchors to ground flying drakes.' },
      { lvl: 46, name: 'Auto-Harvest Trap Mechanism', desc: 'Trapped pelts and meat auto-collect to bag.' },
      { lvl: 47, name: 'Primal Void Trap', desc: 'Trap multidimensional void beasts in end dungeons.' },
      { lvl: 48, name: 'Titan Snare Line', desc: 'Capture raid bosses and hold them for 5 ticks.' },
      { lvl: 49, name: 'Flawless Trap Trigger', desc: '100% trap success rate with zero misfires.' },
      { lvl: 50, name: 'Grand Trapper of PRIMA', desc: 'Unlock Master Trapper title and trophy skin.' },
      { lvl: 50, name: 'Mastery: Primal Catcher', desc: 'Double yield of rare pelts and live captured beasts.' }
    ]
  },
  sailing: {
    id: 'sailing',
    name: 'Sailing',
    icon: '⛵',
    category: 'Utility',
    description: 'Building reed rafts, carving war canoes, river navigation, and archipelago exploration.',
    unlocks: [
      { lvl: 1, name: 'Papyrus Reed Raft', desc: 'Build simple reed rafts to cross shallow rivers.' },
      { lvl: 3, name: 'Paddle Crafting', desc: 'Carve wooden paddles increasing river travel speed.' },
      { lvl: 5, name: 'River Current Reading', desc: 'Navigate upstream with 50% reduced stamina drain.' },
      { lvl: 8, name: 'Dugout Canoe', desc: 'Hollow out pine logs into sturdy single-person canoes.' },
      { lvl: 10, name: 'River Fishing Rig', desc: 'Fish from moving watercraft on the Primeval River.' },
      { lvl: 12, name: 'Wicker Sail Rigging', desc: 'Catch river winds to travel effortlessly downstream.' },
      { lvl: 15, name: 'Outrigger Canoe', desc: 'Build stabilized outriggers for lake navigation.' },
      { lvl: 18, name: 'Swift Water Oars', desc: '+25% paddle speed in open waterways.' },
      { lvl: 20, name: 'Bronze Age War Canoe', desc: 'Construct 4-person war canoes with ramming prow.' },
      { lvl: 22, name: 'Submerged Rock Detection', desc: 'Avoid boat damage from underwater boulders.' },
      { lvl: 25, name: 'River Trade Barge', desc: 'Construct cargo barges carrying up to 100 items.' },
      { lvl: 28, name: 'Swamp Punting Pole', desc: 'Navigate shallow rainforest swamps with ease.' },
      { lvl: 30, name: 'Great Lake Longboat', desc: 'Build multi-oar longboats for northern lakes.' },
      { lvl: 32, name: 'River Rapid Navigation', desc: 'Navigate dangerous white-water rapids without capsizing.' },
      { lvl: 35, name: 'Reinforced Bronze Keel', desc: 'Boats gain +100% hull durability in combat.' },
      { lvl: 38, name: 'Naval Ballista Mount', desc: 'Mount bronze spear throwers on war canoes.' },
      { lvl: 40, name: 'Starfall Celestial Galley', desc: 'Construct glowing reed galleys for deep waters.' },
      { lvl: 42, name: 'Abyss River Diving Rig', desc: 'Dive into underwater dungeons from your boat.' },
      { lvl: 44, name: 'Wind Whisperer Sail', desc: 'Travel at top speed regardless of wind direction.' },
      { lvl: 46, name: 'Fleet Command', desc: 'Command automated trade barges across all cities.' },
      { lvl: 47, name: 'Immortal Hull Coating', desc: 'Boats become completely immune to sinking.' },
      { lvl: 48, name: 'Leviathan Ram', desc: 'Ram river bosses dealing 200 blunt damage.' },
      { lvl: 49, name: 'Oceanic Horizon Crossing', desc: 'Sail beyond continental rivers to uncharted seas.' },
      { lvl: 50, name: 'High Admiral of PRIMA', desc: 'Unlock Lord of the Waves title and admiral helm.' },
      { lvl: 50, name: 'Mastery: Sovereign of Waters', desc: 'Travel on all water at 200% base sprint speed.' }
    ]
  }
};

export function getSkillDef(skillId) {
  return SKILL_DEFINITIONS[skillId] || null;
}

export function getAllSkills() {
  return Object.values(SKILL_DEFINITIONS);
}

export function getSkillTier(level) {
  if (level <= 5) return 1;
  if (level <= 10) return 2;
  if (level <= 15) return 3;
  if (level <= 20) return 4;
  if (level <= 25) return 5;
  if (level <= 30) return 6;
  if (level <= 35) return 7;
  if (level <= 40) return 8;
  if (level <= 45) return 9;
  return 10;
}

export function getUnlocksForLevel(skillId, currentLevel) {
  const def = SKILL_DEFINITIONS[skillId];
  if (!def) return [];
  return def.unlocks.filter(u => u.lvl <= currentLevel);
}

// 0-50 Exponential XP Curve for 10 Tiers
const XP_TABLE = new Array(51).fill(0);
let currentXpSum = 0;
for (let lvl = 1; lvl <= 50; lvl++) {
  XP_TABLE[lvl] = Math.floor(currentXpSum / 4);
  const diff = Math.floor(lvl + 300 * Math.pow(2, lvl / 7.0));
  currentXpSum += diff;
}

export function getLevelForXp(xp) {
  for (let lvl = 50; lvl >= 1; lvl--) {
    if (xp >= XP_TABLE[lvl]) return lvl;
  }
  return 1;
}

export function getXpForLevel(lvl) {
  if (lvl < 1) return 0;
  if (lvl > 50) return XP_TABLE[50];
  return XP_TABLE[lvl];
}
